import os

DEBUG = True
SECRET_KEY = os.urandom(128)

# DATABASE CONFIG
MONGODB_DB = 'compost'
# MONGODB_HOST = 'ds127190.mlab.com'
MONGODB_HOST = 'localhost'
# MONGODB_PORT = 27190
MONGODB_PORT = 27017
MONGODB_USERNAME = 'yannis'
MONGODB_PASSWORD = 'spacegr'

SECURITY_TRACKABLE = True
SECURITY_CONFIRMABLE = False
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_POST_LOGIN_VIEW = '/dashboard'
SECURITY_POST_REGISTER_VIEW = '/dashboard'
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_PASSWORDLESS = False
SECURITY_PASSWORD_HASH = 'sha512_crypt'
SECURITY_PASSWORD_SALT = "dkljsarlh5oqy89n8y78cuiyweort/3.64,'32cq[ pltwp4[5tq,uwc p349cq nw78qqoq2y345qb5v"
